import pygame
key_list = [
    (pygame.K_BACKSPACE, "BACKSPACE"),
    (pygame.K_TAB, "TAB"),
    (pygame.K_RETURN, "ENTER"),
    (pygame.K_SPACE, "SPACEBAR"),
    (pygame.K_COMMA, "COMMA"),
    (pygame.K_MINUS, "-"),
    (pygame.K_PERIOD, "PERIOD"),
    (pygame.K_SLASH, "/"),
    (pygame.K_0, "0"),
    (pygame.K_1, "1"),
    (pygame.K_2, "2"),
    (pygame.K_3, "3"),
    (pygame.K_4, "4"),
    (pygame.K_5, "5"),
    (pygame.K_6, "6"),
    (pygame.K_7, "7"),
    (pygame.K_8, "8"),
    (pygame.K_9, "9"),
    (pygame.K_SEMICOLON, ";"),
    (pygame.K_EQUALS, "="),
    (pygame.K_LEFTBRACKET, "["),
    (pygame.K_RIGHTBRACKET, "]"),
    (pygame.K_BACKSLASH, "BACKSLASH"),
    (pygame.K_BACKQUOTE, "`"),
    (pygame.K_a, "A"),
    (pygame.K_b, "B"),
    (pygame.K_c, "C"),
    (pygame.K_d, "D"),
    (pygame.K_e, "E"),
    (pygame.K_f, "F"),
    (pygame.K_g, "G"),
    (pygame.K_h, "H"),
    (pygame.K_i, "I"),
    (pygame.K_j, "J"),
    (pygame.K_k, "K"),
    (pygame.K_l, "L"),
    (pygame.K_m, "M"),
    (pygame.K_n, "N"),
    (pygame.K_o, "O"),
    (pygame.K_p, "P"),
    (pygame.K_q, "Q"),
    (pygame.K_r, "R"),
    (pygame.K_s, "S"),
    (pygame.K_t, "T"),
    (pygame.K_u, "U"),
    (pygame.K_v, "V"),
    (pygame.K_w, "W"),
    (pygame.K_x, "X"),
    (pygame.K_y, "Y"),
    (pygame.K_z, "Z"),
    (pygame.K_DELETE, "DELETE"),
    (pygame.K_KP0, "KEYPAD 0"),
    (pygame.K_KP1, "KEYPAD 1"),
    (pygame.K_KP2, "KEYPAD 2"),
    (pygame.K_KP3, "KEYPAD 3"),
    (pygame.K_KP4, "KEYPAD 4"),
    (pygame.K_KP5, "KEYPAD 5"),
    (pygame.K_KP6, "KEYPAD 6"),
    (pygame.K_KP7, "KEYPAD 7"),
    (pygame.K_KP8, "KEYPAD 8"),
    (pygame.K_KP9, "KEYPAD 9"),
    (pygame.K_KP_MULTIPLY, "KP MULTIPLY"),
    (pygame.K_KP_DIVIDE, "KP DIVIDE"),
    (pygame.K_KP_MINUS, "KP MINUS"),
    (pygame.K_KP_PLUS, "KP PLUS"),
    (pygame.K_KP_ENTER, "KP ENTER"),
    (pygame.K_UP, "UP"),
    (pygame.K_DOWN, "DOWN"),
    (pygame.K_LEFT, "LEFT"),
    (pygame.K_RIGHT, "RIGHT"),
    (pygame.K_HOME, "HOME"),
    (pygame.K_END, "END"),
    (pygame.K_PAGEUP, "PAGEUP"),
    (pygame.K_PAGEDOWN, "PAGEDOWN"),
    (pygame.K_F1, "F1"),
    (pygame.K_F2, "F2"),
    (pygame.K_F3, "F3"),
    (pygame.K_F4, "F4"),
    (pygame.K_F5, "F5"),
    (pygame.K_F6, "F6"),
    (pygame.K_F7, "F7"),
    (pygame.K_F8, "F8"),
    (pygame.K_F9, "F9"),
    (pygame.K_F10, "F10"),
    (pygame.K_F11, "F11"),
    (pygame.K_F12, "F12"),
    (pygame.K_F13, "F13"),
    (pygame.K_F14, "F14"),
    (pygame.K_F15, "F15"),
    (pygame.K_CAPSLOCK, "CAPSLOCK"),
    (pygame.K_SCROLLOCK, "SCROLLOCK"),
    (pygame.K_RSHIFT, "RIGHT SHIFT"),
    (pygame.K_LSHIFT, "LEFT SHIFT"),
    (pygame.K_RCTRL, "RIGHT CONTROL"),
    (pygame.K_LCTRL, "LEFT CONTROL"),
    (pygame.K_RALT, "RIGHT ALT"),
    (pygame.K_LALT, "LEFT ALT")
]